import type { Config, Group } from './types.js';

/**
 * Built-in sensitive names, normalised (lowercase, no separators). A name in a log call matches by its last one to
 * three words, so `userEmail` matches `email` and `x-api-key` matches `apikey`.
 */
export const DEFAULT_KEYS: Record<Group, string[]> = {
  credentials: [
    'password',
    'passwd',
    'pwd',
    'passphrase',
    'secret',
    'clientsecret',
    'secretkey',
    'privatekey',
    'apikey',
    'token',
    'authorization',
    'cookie',
    'setcookie',
    'jwt',
    'bearer',
    'credentials',
    'otp',
  ],
  pii: [
    'email',
    'emailaddress',
    'firstname',
    'lastname',
    'fullname',
    'phone',
    'phonenumber',
    'mobile',
    'mobilenumber',
    'tel',
    'ssn',
    'socialsecuritynumber',
    'nino',
    'nationalinsurancenumber',
    'dob',
    'dateofbirth',
    'birthdate',
    'passport',
    'passportnumber',
    'insurancenumber',
    'healthinsuranceid',
    'nhsnumber',
    'mbi',
    // A bare `address` is left out on purpose: `server.address()` is a bind address, not a person's.
    'streetaddress',
    'homeaddress',
    'residentialaddress',
    'useraddress',
    'customeraddress',
    'billingaddress',
    'shippingaddress',
    'mailingaddress',
    'postaladdress',
    'street',
    'postcode',
    'zip',
    'ip',
    'ipaddress',
    'clientip',
    'remoteaddress',
    'xforwardedfor',
    'recipient',
  ],
  financial: ['creditcard', 'cardnumber', 'cvv', 'cvc', 'iban', 'accountnumber'],
};

export const DEFAULT_CONFIG: Config = {
  keys: { groups: ['credentials', 'pii', 'financial'], add: [], allow: [] },
  sinks: [],
  safeCalls: [
    'mask',
    'redact',
    'hash',
    'sanitize',
    'sanitise',
    'scrub',
    'anonymize',
    'anonymise',
    'obfuscate',
    'encrypt',
  ],
  ignore: [
    '**/node_modules/**',
    '**/dist/**',
    '**/build/**',
    '**/coverage/**',
    '**/.git/**',
    '**/*.d.ts',
    '**/*.min.js',
    '**/*.test.*',
    '**/*.spec.*',
    '**/__tests__/**',
    '**/__mocks__/**',
    '**/__fixtures__/**',
    '**/test/**',
    '**/tests/**',
    '**/spec/**',
    '**/e2e/**',
    '**/playwright/**',
    '**/cypress/**',
  ],
  rules: {
    'no-sensitive-key': 'error',
    'no-whole-object': 'error',
    'no-secret-literal': 'error',
    'no-pii-value': 'warn',
    'suppression-needs-reason': 'error',
  },
};
